/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenreIdRouteImport } from './routes/genre.$id'
import { Route as AnimeIdRouteImport } from './routes/anime.$id'
import { Route as WatchIdEpRouteImport } from './routes/watch.$id.$ep'
import { Route as ApiAnimeProxyRouteImport } from './routes/api/anime.proxy'
import { Route as ApiAnimeStreamEpisodeIdRouteImport } from './routes/api/anime.stream.$episodeId'
import { Route as ApiAnimeEpisodesIdRouteImport } from './routes/api/anime.episodes.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreIdRoute = GenreIdRouteImport.update({
  id: '/genre/$id',
  path: '/genre/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdRoute = AnimeIdRouteImport.update({
  id: '/anime/$id',
  path: '/anime/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdEpRoute = WatchIdEpRouteImport.update({
  id: '/watch/$id/$ep',
  path: '/watch/$id/$ep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnimeProxyRoute = ApiAnimeProxyRouteImport.update({
  id: '/api/anime/proxy',
  path: '/api/anime/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnimeStreamEpisodeIdRoute = ApiAnimeStreamEpisodeIdRouteImport.update({
  id: '/api/anime/stream/$episodeId',
  path: '/api/anime/stream/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnimeEpisodesIdRoute = ApiAnimeEpisodesIdRouteImport.update({
  id: '/api/anime/episodes/$id',
  path: '/api/anime/episodes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/genres': typeof GenresRoute
  '/search': typeof SearchRoute
  '/anime/$id': typeof AnimeIdRoute
  '/genre/$id': typeof GenreIdRoute
  '/api/anime/proxy': typeof ApiAnimeProxyRoute
  '/watch/$id/$ep': typeof WatchIdEpRoute
  '/api/anime/episodes/$id': typeof ApiAnimeEpisodesIdRoute
  '/api/anime/stream/$episodeId': typeof ApiAnimeStreamEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/genres': typeof GenresRoute
  '/search': typeof SearchRoute
  '/anime/$id': typeof AnimeIdRoute
  '/genre/$id': typeof GenreIdRoute
  '/api/anime/proxy': typeof ApiAnimeProxyRoute
  '/watch/$id/$ep': typeof WatchIdEpRoute
  '/api/anime/episodes/$id': typeof ApiAnimeEpisodesIdRoute
  '/api/anime/stream/$episodeId': typeof ApiAnimeStreamEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/genres': typeof GenresRoute
  '/search': typeof SearchRoute
  '/anime/$id': typeof AnimeIdRoute
  '/genre/$id': typeof GenreIdRoute
  '/api/anime/proxy': typeof ApiAnimeProxyRoute
  '/watch/$id/$ep': typeof WatchIdEpRoute
  '/api/anime/episodes/$id': typeof ApiAnimeEpisodesIdRoute
  '/api/anime/stream/$episodeId': typeof ApiAnimeStreamEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/genres'
    | '/search'
    | '/anime/$id'
    | '/genre/$id'
    | '/api/anime/proxy'
    | '/watch/$id/$ep'
    | '/api/anime/episodes/$id'
    | '/api/anime/stream/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/genres'
    | '/search'
    | '/anime/$id'
    | '/genre/$id'
    | '/api/anime/proxy'
    | '/watch/$id/$ep'
    | '/api/anime/episodes/$id'
    | '/api/anime/stream/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/genres'
    | '/search'
    | '/anime/$id'
    | '/genre/$id'
    | '/api/anime/proxy'
    | '/watch/$id/$ep'
    | '/api/anime/episodes/$id'
    | '/api/anime/stream/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  GenresRoute: typeof GenresRoute
  SearchRoute: typeof SearchRoute
  AnimeIdRoute: typeof AnimeIdRoute
  GenreIdRoute: typeof GenreIdRoute
  ApiAnimeProxyRoute: typeof ApiAnimeProxyRoute
  WatchIdEpRoute: typeof WatchIdEpRoute
  ApiAnimeEpisodesIdRoute: typeof ApiAnimeEpisodesIdRoute
  ApiAnimeStreamEpisodeIdRoute: typeof ApiAnimeStreamEpisodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/$id': {
      id: '/genre/$id'
      path: '/genre/$id'
      fullPath: '/genre/$id'
      preLoaderRoute: typeof GenreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id': {
      id: '/anime/$id'
      path: '/anime/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof AnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id/$ep': {
      id: '/watch/$id/$ep'
      path: '/watch/$id/$ep'
      fullPath: '/watch/$id/$ep'
      preLoaderRoute: typeof WatchIdEpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anime/proxy': {
      id: '/api/anime/proxy'
      path: '/api/anime/proxy'
      fullPath: '/api/anime/proxy'
      preLoaderRoute: typeof ApiAnimeProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anime/stream/$episodeId': {
      id: '/api/anime/stream/$episodeId'
      path: '/api/anime/stream/$episodeId'
      fullPath: '/api/anime/stream/$episodeId'
      preLoaderRoute: typeof ApiAnimeStreamEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anime/episodes/$id': {
      id: '/api/anime/episodes/$id'
      path: '/api/anime/episodes/$id'
      fullPath: '/api/anime/episodes/$id'
      preLoaderRoute: typeof ApiAnimeEpisodesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  GenresRoute: GenresRoute,
  SearchRoute: SearchRoute,
  AnimeIdRoute: AnimeIdRoute,
  GenreIdRoute: GenreIdRoute,
  ApiAnimeProxyRoute: ApiAnimeProxyRoute,
  WatchIdEpRoute: WatchIdEpRoute,
  ApiAnimeEpisodesIdRoute: ApiAnimeEpisodesIdRoute,
  ApiAnimeStreamEpisodeIdRoute: ApiAnimeStreamEpisodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
